
CREATE TABLE  GP_ROOM_HISTORY
   (	ROOM_ID NUMBER(25,0) NOT NULL ENABLE, 
	SQUAREFEET NUMBER(25,0) NOT NULL ENABLE, 
	ROOMTYPE VARCHAR2(25) NOT NULL ENABLE, 
	ROOMDESCRIPTION VARCHAR2(25) NOT NULL ENABLE
   ) ;